name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.MD'
      - '*.ignore'
      - LICENSE
     
jobs:
  
  circtools:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # Run everything via the Bioconductor docker image as it has almost all dependencies preinstalled
      - name: devtools-check-docker
        run: |
          bioc_install='BiocManager::install(c("limma", "ggplot2"))'
          dev_check='devtools::check("/circtools/")'
          dev_doc='devtools::document("/circtools/")'
          testthat='testthat::test_file("/circtools/tests/testthat/all_tests.R")'
          docker run -v "$(pwd)":"/circtools/" bioconductor/bioconductor_docker:RELEASE_3_18 Rscript --vanilla -e "${bioc_install}; ${dev_check}; ${dev_doc}; ${testthat}"